# NORMALIZATION PROBLEM
- Normalization is one of the most basic preprocessing techniques in data analytics. This involves centering and scaling process. Centering means subtracting the data from the mean and scaling means dividing with its standard deviation. Mathematically, normalization can be expressed as: 𝑍 = ( 𝑋 − 𝑥̅ ) / 𝜎.
-  In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and .std() calls. In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized ndarray as X_normalized.npy

In [89]:
#import numpy library
import numpy as np

In [91]:
#creates and stores in array X values ranging frorm 1 to 25
X = np.random.random(25)
X

array([0.58798523, 0.2741849 , 0.2499425 , 0.65486895, 0.7149238 ,
       0.68591247, 0.1020913 , 0.98164708, 0.11681756, 0.98351311,
       0.33718338, 0.5410571 , 0.60669832, 0.2257825 , 0.72669591,
       0.50825912, 0.89763404, 0.04654219, 0.5503276 , 0.99625054,
       0.27093183, 0.54613335, 0.33881693, 0.39917331, 0.79994593])

In [93]:
#shapes the 1d array into a 5 by 5 2d array
X = X.reshape(5, 5)
X

array([[0.58798523, 0.2741849 , 0.2499425 , 0.65486895, 0.7149238 ],
       [0.68591247, 0.1020913 , 0.98164708, 0.11681756, 0.98351311],
       [0.33718338, 0.5410571 , 0.60669832, 0.2257825 , 0.72669591],
       [0.50825912, 0.89763404, 0.04654219, 0.5503276 , 0.99625054],
       [0.27093183, 0.54613335, 0.33881693, 0.39917331, 0.79994593]])

In [95]:
#computes the element-wise mean
mean = X.mean()
mean

0.5257327586326147

In [97]:
#computes the element-wise standard deviation
sd = X.std()
sd

0.2785576838837114

In [99]:
#Normalization formula
normalized = (X - mean)/ sd

In [101]:
normalized

array([[ 0.22348144, -0.90303686, -0.99006518,  0.46358868,  0.67918085],
       [ 0.57503245, -1.52083926,  1.63669627, -1.46797313,  1.64339517],
       [-0.67687731,  0.05501318,  0.29065996, -1.07679766,  0.72144179],
       [-0.06272896,  1.33509611, -1.72025613,  0.08829353,  1.68912153],
       [-0.91471513,  0.07323652, -0.67101299, -0.4543384 ,  0.98440353]])

In [103]:
#Normalized array is saved to "X_normalized"
np.save( "X_normalized.npy", normalized )

In [105]:
#loads the normalized array
data = np.load("X_normalized.npy")
data

array([[ 0.22348144, -0.90303686, -0.99006518,  0.46358868,  0.67918085],
       [ 0.57503245, -1.52083926,  1.63669627, -1.46797313,  1.64339517],
       [-0.67687731,  0.05501318,  0.29065996, -1.07679766,  0.72144179],
       [-0.06272896,  1.33509611, -1.72025613,  0.08829353,  1.68912153],
       [-0.91471513,  0.07323652, -0.67101299, -0.4543384 ,  0.98440353]])